### ISSUE TITLE
Right click on doors

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#157]
Can we implement a right click on a 3D object in the 3D editor ? It should popup a window of properties that can be edited. We need it for the door category that will show a dropdown with other doors existing in all scenes.

**Implementation steps**

- [x] Make the right click implementation (Dimitris)
- [x] Make the 2D gui to display above the 3d object (a panel with a dropdown and a field to place the id of  the door ) (Tasos)
- [ ] Query the wp database to find all the doors existing in the game (Stathis)
     a. Get all jsons for the scenes that belong to the game
     b. Extract door information from the scenes and return it to a php ajax
- [ ] Get from the php ajax the door information and put it in the dropdown (Dimitris)
- [x] Save in the json the information for the target door (dimitrio)

**Comment by jimver04** [comment]
Now the door info is saved and retrieved from json. I merged tasos GUI with my changes.
I have a bug in the javascript side. If you click first a door and change the values, and the click on a second door, the values are passed from the second door to the first door. I will fix it. Something is happening with the javascript.

**Comment by jimver04** [comment]
Minor bug was fixed in 293b866

**Comment by jimver04** [comment]
Stathi now we are waiting for you to make the php that 

1. Gets all jsons for the scenes that belong to the game
2. Gets the information about the doors . I have modified the json format so that the door fields are also saved in the json like this: 
```
		"mydoora_1507541772" : {
			"position" : [0,0,-21.738358259867],
			"rotation" : [0,0,0],
			"quaternion" : [0,0,0,1],
			"scale"	   : [1,1,1],
			"fnPath" : "/Models/",
			"assetid" : "1513",
			"fnObj" : "d3e613c6816493e83f38dc0ce7ed0c91_objmydoora.txt",
			"fnObjID" : "1516",
			"categoryName" : "Door",
			"categoryID" : "523",
			"diffImage" : "http://127.0.0.1:8080/digiart-project_Jan17/wpunity_asset3d/mydoora/attachment/1514/",
			"diffImageID" : "1514",
			"image1id" : "",
		   "doorName_source" : "1111111",
		   "doorName_target" : "doorGreen",
		   "sceneName_target" : "SecondScene",
			"fnMtl" : "ae78c2bf26a1471a648044d8e1cac14d_materialmydoora.txt",
			"fnMtlID" : "1515",
			"children" : {
			}
		},
```

I want you to get me all the 
```
		   "doorName_source" : "1111111",
		   "doorName_target" : "doorGreen",
		   "sceneName_target" : "SecondScene",
```
Existing in the scene where the categoryName == "Door"

**Comment by jimver04** [comment]
It is done without ajax. The door information is fixed throughout the scene and it is fetched with standard php and javascript variable transformation with json_encode from php. :)

```echo "var doorsAll=".json_encode($doorsAllInfo).";";```
