### ISSUE TITLE
General Testing of master branch

### ISSUE THREAD

**Issue by jimver04** [DigiArt-project/WordpressUnity3DEditor#168]
Let us discuss the following:

- [ ] Wordpress Debug to true Warnings  #151
- [ ] Archaeology template #155 
- [x] Game version number input #163 
- [x] Right click on doors on 3D editor (load - save json)  #157
- [x] Support multiple images (pending) #166
- [x] 'Resources' folder for sprite jpgs #156
- [x] Add also videos in 'Resources' folder
- [x] Assembly Wonder around scenes
- [x] obj meta settings: remove all but guid and timestamp (check if it is closed)
- [x] obj save  as 'mymodel_CollidersNoOptimization.obj' for 'Sites' category when the Unity3D game is generated #167
- [x] iframe parameters (implement Tasos, add wpunity_game id)
- [ ] analytics connect (dimitrios)

**Comment by jimver04** [comment]
2: Warnings
Notice: Undefined variable: tt_id in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-types-scenes-yaml.php on line 17553

Notice: Trying to get property of non-object in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-core-functions.php on line 352

Notice: Undefined variable: post in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-types-assets-data.php on line 46

Notice: Trying to get property of non-object in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-types-assets-data.php on line 46

Notice: Undefined variable: post in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-types-assets-data.php on line 47

Notice: Trying to get property of non-object in C:\xampp\htdocs\digiart-project_Jan17\wp-content\plugins\wordpressunity3deditor\includes\wpunity-types-assets-data.php on line 47

**Comment by jimver04** [comment]
Hi Dimitrios,

Yes, thank you. Here are two examples of the info, I have been getting so far:

wpunity_scene=981
wpunity_game=942
scene_type=scene

and

wpunity_scene=224
wpunity_game=221
scene_type=scene

Does this look correct?

I’m not sure about the mappings from game number to game type, though, do you have a table with that information somewhere or am I missing something? If you have human readable codes, I must be getting the wrong information

It would be great to have the lab version number too, just to make sure we’re pulling the right data, and codes for the location too.

For the review demo, I presume we won’t limit location to our own location, since we can’t see the data then, but going forward that’s something we could just enable.
